/// Flutter icons Porco
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Porco
///      fonts:
///       - asset: fonts/Porco.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Porco {
  Porco._();

  static const _kFontFam = 'Porco';
  static const _kFontPkg = null;

  static const IconData icon_awesome_piggy_bank = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
